### ISSUE TITLE
Stuck Can't Download

### ISSUE THREAD

**Issue by RealWolvesUnited** [iDerp/fav-releases#1]
Can't Install stuck at the loading bar

**Comment by RealWolvesUnited** [comment]
![image](https://user-images.githubusercontent.com/56106431/67627690-060a4b00-f82f-11e9-9b53-5ad31931a62a.png)

**Comment by iDerp** [comment]
-Issue resolved over Discord

Solution: Uninstalling via Control panel first and then installing (usually isn't needed)
